source 'http://rubygems.org'

gem 'rails'
gem 'activesupport'

gem 'rack'
gem 'mongrel', '1.2.0.pre2'
gem 'mongrel_cluster'
gem 'daemons'

gem 'haml-rails'
gem 'simple_form'
gem 'devise'
gem 'carrierwave'
gem "delayed_job"
gem 'delayed_job_active_record'
gem "daemons"

gem 'sys-filesystem'
gem 'rubyzip'

group :assets do
  gem 'sass-rails'
  # gem 'coffee-rails'
  # gem 'uglifier'
  # gem 'therubyracer'
end

gem 'jquery-rails'
gem 'rspec-rails'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
gem 'capistrano'

group :test do
  gem 'rake'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'cucumber-rails', :require => false
  gem 'cucumber'
  gem 'launchy'
  gem 'simplecov'

  gem 'factory_girl_rails'
  gem 'shoulda', '>= 3.0.0.beta'
  gem 'ruby-prof'
end

group :development do
 gem 'sqlite3'
 gem 'ruby-prof'
end

group :production do
#  gem 'activerecord-mysql2-adapter'
#  gem 'mysql2'
end
